# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosssite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=1024, upload_to=b'profile_images'),
        ),
    ]
