# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosssite', '0002_userprofile_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blog_xml',
            field=models.URLField(blank=True),
        ),
    ]
