# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fosssite', '0003_auto_20160817_1651'),
        ('fosssite', '0003_userprofile_blog_xml'),
    ]

    operations = [
    ]
