# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fosssite', '0003_auto_20160808_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='profileuser',
        ),
    ]
