# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosssite', '0004_auto_20160817_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='handle',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
