# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosssite', '0005_auto_20160827_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributions',
            name='contribution_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='organization',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='ticket_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='event_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='event_name',
            field=models.CharField(max_length=200),
        ),
    ]
