# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosssite', '0006_auto_20160817_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='example',
            field=models.URLField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebookurl',
            field=models.URLField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='githuburl',
            field=models.URLField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='handle',
            field=models.CharField(blank=True, default=b'', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lnkdnurl',
            field=models.URLField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitterurl',
            field=models.URLField(blank=True, default=b''),
        ),
    ]
