# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosssite', '0006_auto_20160827_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributions',
            name='contribution_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='ticket_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='event_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='event_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
