# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 18:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fosssite', '0008_auto_20160827_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributions',
            name='contributionsuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='speakersuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
