# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fosssite', '0002_auto_20160822_1811'),
        ('fosssite', '0009_auto_20160827_1824'),
    ]

    operations = [
    ]
