# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-28 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fosssite', '0004_merge'),
        ('fosssite', '0009_auto_20160827_1824'),
    ]

    operations = [
    ]
