# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosssite', '0010_auto_20160817_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'profile_images'),
        ),
    ]
